# Generated by Django 5.2.5 on 2025-12-07 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0003_car_color_car_engine_size_car_fuel_type_car_mileage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the request was submitted.')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the rental request.', max_length=10)),
                ('car', models.ForeignKey(help_text='The car being requested for rental.', on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='CarRentalApp.car')),
                ('customer', models.ForeignKey(help_text='The customer who placed the request.', on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='CarRentalApp.customer')),
            ],
        ),
    ]
