# Generated by Django 5.2.5 on 2025-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0004_rentalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('MAINTENANCE', 'Maintenance'), ('UNLISTED', 'Unlisted')], default='Available', max_length=20),
        ),
    ]
