# Generated by Django 5.2.5 on 2025-12-07 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0005_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='CarRentalApp.customer')),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='CarRentalApp.rentalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
